### ISSUE TITLE
Kernel panic on vmware workstation 

### ISSUE THREAD

**Issue by agalq12** [portasynthinca3/neutron#9]
Версия 0.5.0 кидает kernel panic
Версия 0.4.9 работает
Я тестирую на VMware Workstation 15.5.1
https://priscree.ru/img/fbbb77617879a9.png
https://priscree.ru/img/0493e63a013e62.png

**Comment by portasynthinca3** [comment]
Похоже, что процессором, эмулируемым VMWare, не поддерживается механизм страниц памяти, или что-то связанное с этим. Не могли бы вы скинуть логи работы виртуальной машины и её настройки?

**Comment by agalq12** [comment]
Лог: https://pastebin.com/NxamhgfJ
Настройки: https://pastebin.com/ejEDpD3N

**Comment by portasynthinca3** [comment]
Похоже, проблема была в попытке включить идентификаторы контекста процессов (PCID), пока нижние 12 бит регистра CR3 не очищены. Фикс вроде как готов, будет в следующем релизе.

Благодарю за помощь проекту!

**Comment by agalq12** [comment]
Проблема до сих пор осталась
https://priscree.ru/img/a8ae6cef102355.png
Лог:https://pastebin.com/uLgJiPp6

**Comment by portasynthinca3** [comment]
Добавил определение фич через CPUID и отключение PCID, если они не поддерживаются процессором. Судя по Вашим логам, проблема в этом. Просьба собрать последний коммит и протестировать.

**Comment by agalq12** [comment]
Работает!
https://priscree.ru/img/e0f9dd75955cb6.png
